demo/config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'

  get 'say/goodbye'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

demo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

demo/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
    @hour_from_now = 1.hour.from_now.localtime
    @files = Dir.glob('*')
  end

  def goodbye
  end
end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/say_helper.rb
module SayHelper
end

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

demo/app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>
  It was nice having you here.
</p>
<p>
Time to say
<%= link_to "Hello?", say_hello_path %>! </p>

demo/app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>
<p>It is now <%= @time %> </p>
<p>In one hour it will be <%= @hour_from_now %></p>
<p><%= "con" + "cat" %></p>
<p><%= 6 * 12 %> is the answer to 6 x 12.</p>
<p>These are all the files in this directory:</p>
<ul>
<% @files.each do |file| %>
<li>file name is: <%= file %></li>
<% end %>
</ul>
<p>Time to say <%= link_to "Goodbye", say_goodbye_path %>!</p>